#centro de control de perfiles 
server:
 port: 8090
spring:
 profiles:
   active: dev
---
#configuracion developer
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2
      
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
 
info:
  env:
    enabled: true  
      
logging:
  file:
    name: logback.xml
    path: src/main/resources/logback.xml
    
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html
  show-actuator: true
---
#Local configuracion

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2
      
logging:
  file:
    name: logback.xml
    path: src/main/resources/logback.xml
    
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html
  show-actuator: true
---

#stg configuracion

spring:
  config:
    activate:
      on-profile: stg
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2
      
logging:
  file:
    name: logback.xml
    path: src/main/resources/logback.xml
    
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html
  show-actuator: true
---

#prod configuracion

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2
      
logging:
  file:
    name: logback.xml
    path: src/main/resources/logback.xml
    
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html
  show-actuator: true




    

